environment: prod
domains:
  - bts-crew.com
  - www.bts-crew.com

smtp:
  host: smtp.gmail.com
  port: 587
  encryption: tls
  auth: true

logging:
  driver: stack

google-analytics-code: UA-150311689-2
