blank_issues_enabled: false
contact_links:
  - name: â” Ask a Question
    url: https://github.com/backstage-technical-services/website/discussions/categories/questions
    about: Ask any other question
  - name: ğŸ’¬ Open a Discussion
    url: https://github.com/backstage-technical-services/website/discussions/categories/discussions
    about: Use this to have a general discussion on any topic
  - name: ğŸ“ Open a Request for Comments (RFC)
    url: https://github.com/backstage-technical-services/website/discussions/categories/requests-for-comment-rfcs
    about: Use this for a proposal which needs feedback from the wider community before it can be approved and worked on
